c_compiler:              # [win]
  - vs2022               # [win]
cxx_compiler:            # [win]
  - vs2022               # [win]
c_stdlib_version:        # [win]
  - 2022.14              # [win]

c_compiler_version:         # [osx]
  - 19                      # [osx]
cxx_compiler_version:       # [osx]
  - 19                      # [osx]